Select AI racers in menu.
David-Hanna/CS483New pull request #178
Opened 2017-04-05 19:14 UTC by David-Hanna

2017-04-05 19:52 UTC, bradcooper314 requested changes
1. There's still a reference to the old uiJoined variable in State Player Select preventing it from compiling.

2. When a player joins, the graphics say they are highlighting the driver select but they cannot press up. When they press down, it stays on driver select and then you can press up. The coded default is human/bot control, but the graphic default is driver select.

3. I can't explain why, but joining another player, changing them to bot, and then cancelling them permanently increases m_uiNumPlayers by 1 and permanently decreases m_uiNumAIPlayers by 1 (resulting in underflow to 65million). This is repeatable too.

4. Kind of a design choice, but you are implying you would need four controllers to select four racers for AI. What if I only have my one keyboard input? Do I race with only one character?

5. Matt added some Player5 fixes to handle cases with four humans + 1 AI when it was still hardcoded. That stuff can be cleaned up now.

2017-04-05 20:32 UTC, David-Hanna commented
1. I will have to take a second look at this one, as it was compiling and running on my machine when I submitted the PR.

2. This also seems like something I would have encountered... I can remember explicitly this not being the case but I'll take another look.

3. I can understand this being the case if I made the mistake I think I made.

4. You can just add them with the extra keyboard controls.

5. I'm not aware of what those exact fixes are.

2017-04-16 20:37 UTC, David-Hanna commented
Got a second look from both myself and MacIntosh and we could only reproduce the first bug and only in debug (which is why I wasn't aware of it), which is fixed. We also noted 4 is a valid point but would probably be a significant menu redesign that's not really scheduled to be done at this point. The task was only meant to be short.

2017-04-16 21:39 UTC, MatthewWhite approved these changes

2017-04-16 21:40 UTC, merged