Feature/rotating models
David-Hanna/CS483New pull request #179
Opened 2017-04-05 19:15 UTC by David-Hanna

2017-04-05 19:25 UTC, bradcooper314 requested changes
Some kind of desync happens as the player select screen models rotate, probably because the y-axis of the driver isn't vertically aligned with the y-axis of the kart. After 1 or 2 spins, the kart's steering wheel is going into the driver's chest.

The bowling ball looks good though...

2017-04-05 19:25 UTC, bradcooper314 commented on HeatStroke/GOComponents/Components/ComponentRotateOverTime.cpp
> +	return new ComponentRotateOverTime(
Is anything changing here or is this a leftover comment?

2017-04-05 20:25 UTC, David-Hanna commented on HeatStroke/GOComponents/Components/ComponentRotateOverTime.cpp
> +	return new ComponentRotateOverTime(
Leftover.

2017-04-05 20:28 UTC, David-Hanna commented
Right, the issue is actually that the center of the game object that it's rotating around isn't the same as the center of the model as created in Blender as a result of "sitting" him in the kart. So this is quite a difficult issue to fix as I've already expanded on the models into animations and would have to change frames upon frames of models to now be centered around the correct point and equally offset to make up for the positional difference.

2017-04-06 19:09 UTC, bradcooper314 commented
Rather than rotating them individually, can we do something similar to what we do in the races. Have them both be a child of an empty adult GameObject that rotates, and do the usual destroy/create when changing characters except now you would add them again as a child. Would this work?

2017-04-16 19:53 UTC, David-Hanna commented
Fixed.

2017-04-16 21:17 UTC, MatthewWhite approved these changes

2017-04-16 21:18 UTC, merged